DROP Materialized View STGMGR.MV_IE_COMBINED_IDRP_STATUS;

CREATE Materialized View STGMGR.MV_IE_COMBINED_IDRP_STATUS
TABLESPACE SCPODATA
NOLOGGING
PARALLEL 32
BUILD IMMEDIATE
REFRESH FORCE
ON DEMAND
ENABLE QUERY REWRITE
AS
select  /*+ PARALLEL(comb_a, 32) */ ITEM, LOC, KSN_ID, SRS_DIV_ITEM_SKU, LOC_OWN_CD, IDRP_STATUS_CD
from    STGMGR.IE_COMBINED_IDRP_STATUS comb_a
UNION
select  /*+ PARALLEL(comb_b, 32) */ ITEM, LOC, KSN_ID, SRS_DIV_ITEM_SKU, LOC_OWN_CD, IDRP_STATUS_CD
from    STGMGR.IE_COMBINED_IDRP_STATUS@IDRPPSB_RO comb_b
UNION
select  /*+ PARALLEL(comb_c, 32) */ ITEM, LOC, KSN_ID, SRS_DIV_ITEM_SKU, LOC_OWN_CD, IDRP_STATUS_CD
from    STGMGR.IE_COMBINED_IDRP_STATUS@IDRPPSC_RO comb_c
UNION
select  /*+ PARALLEL(comb_d, 32) */ ITEM, LOC, KSN_ID, SRS_DIV_ITEM_SKU, LOC_OWN_CD, IDRP_STATUS_CD
from    STGMGR.IE_COMBINED_IDRP_STATUS@IDRPPSD_RO comb_d;

GRANT select on STGMGR.MV_IE_COMBINED_IDRP_STATUS to public;

