REGISTER $PIGGYBANK ;

DEFINE TRIM_STRING $TRIM_STRING ;

rmf $ITEM_RPT_GRP_DB2_FILE_WORK_LOCATION

item_rpt_grp_db2_table = LOAD '$ITEM_RPT_GRP_DB2_FILE_INCOMING_LOCATION' USING PigStorage('$FIELD_DELIMITER') AS ($ITEM_RPT_GRP_DB2_FILE_SCHEMA) ;

item_rpt_grp_db2_hadoop_table = FOREACH item_rpt_grp_db2_table GENERATE $ITEM_RPT_GRP_DB2_HADOOP_FILE_SCHEMA;

STORE item_rpt_grp_db2_hadoop_table INTO '$ITEM_RPT_GRP_DB2_FILE_WORK_LOCATION'  USING PigStorage('$FIELD_DELIMITER');
